# LOGGING
LOGGING:
  LOG_FILE: "./logs/logs.log"
  LOG_SIZE_LIMIT: 1000000 # 1MB
  # LOG_SIZE_LIMIT: 1024 # 1KB
  # LOG_LEVEL: "DEBUG"
  LOG_LEVEL: "INFO"
  LOG_FORMAT: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
